// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiUaGF8xnIfBnX1PbcAYi8JBlDK36PaP8',
    appId: '1:450903665496:web:2e0dab101cfb0a9f03932d',
    messagingSenderId: '450903665496',
    projectId: 'task-f507d',
    authDomain: 'task-f507d.firebaseapp.com',
    storageBucket: 'task-f507d.appspot.com',
    measurementId: 'G-MN8RFDJJHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwKpjWbdKB7U3L0LOr53CYGx91Z4Cf3A',
    appId: '1:450903665496:android:6ca3b129e1d94e9803932d',
    messagingSenderId: '450903665496',
    projectId: 'task-f507d',
    storageBucket: 'task-f507d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc5pnC3b3ME1oPq4JnKEdsD3eFLql9N8I',
    appId: '1:450903665496:ios:b647d5bdc31a891203932d',
    messagingSenderId: '450903665496',
    projectId: 'task-f507d',
    storageBucket: 'task-f507d.appspot.com',
    iosClientId: '450903665496-67b6bqv38j2edkoltjmn86j14mn2quqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc5pnC3b3ME1oPq4JnKEdsD3eFLql9N8I',
    appId: '1:450903665496:ios:b647d5bdc31a891203932d',
    messagingSenderId: '450903665496',
    projectId: 'task-f507d',
    storageBucket: 'task-f507d.appspot.com',
    iosClientId: '450903665496-67b6bqv38j2edkoltjmn86j14mn2quqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
